### ISSUE TITLE
How do you disable in tests?

### ISSUE THREAD

**Issue by jim-obrien-orig** [tommy-muehle/go-mnd#2]
This is very inconvenient in writing test cases. Please document the the comment tag to disable the check in a function.

**Comment by mbow** [comment]
I like the linter, but yes being able to turn this off on test files like other linters would be great.

**Comment by jim-obrien-orig** [comment]
You can disable it via the config if you're using golangci-lint. But it would be nice to be able to do it for a function or line in comments.

```
#.golangci.yml:
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
```
