### ISSUE TITLE
Multiplicating two numbers and a duration is not reported

### ISSUE THREAD

**Issue by Crocmagnon** [tommy-muehle/go-mnd#36]
### Short summary 
```go
package main

import (
	"log"
	"time"
)

func main() {
	log.Println(24 * time.Hour) // reported
	log.Println(1 * 24 * time.Hour) // not reported
}
```

### Steps to reproduce the behavior
(See above)

### go-mnd version or commit ref
Running as part of `golangci-lint`:
```console
$ golangci-lint --version
golangci-lint has version 1.54.2 built with go1.21.0 from 411e0bbb on 2023-08-21T12:04:32Z
```

### Go version (output of 'go version')
```console
$ go version
go version go1.21.1 darwin/arm64
```

### Operating system / Environment
macOS 13.5.2 (22G91)

### Expected behavior
Consistency: either both are reported because they're both magic numbers, or none are reported because when multiplied with a Duration the meaning is clear.

### Actual behavior
Only one of the lines is reported: the one with only one number multiplied with a Duration.

**Comment by hendrywiranto** [comment]
Hi,..
I agree with you that multiplying with a duration means that is a clear number, so maybe reporting none would be preferable

**Comment by sierikov** [comment]
As a temporary solution, you can set `ignored-functions` in `.golangci.yml` with a list of ignored functions. For example, for `context`: 

```yaml
  mnd:
    ignored-functions: "context\\.WithDeadline|context\\.WithTimeout|context\\.WithValue"
```

**Comment by ccoVeille** [comment]
That's right, but I would recommend using a format like this that is more readable and maintainable

https://github.com/rameshsunkara/go-rest-api-example/blob/8600367ac2945f25691df2f42599bb6ab2e331a3/.golangci.yml#L133

```yaml
mnd:
      ignored-functions:
        - flag.Arg
        - flag.Duration.*
        - flag.Float.*
        - flag.Int.*
        - flag.Uint.*
        - os.Chmod
        - os.Mkdir.*
        - os.OpenFile
        - os.WriteFile
        - prometheus.ExponentialBuckets.*
        - prometheus.LinearBuckets
```
